### ISSUE TITLE
buildout cannot find quills.app==1.8

### ISSUE THREAD

**Issue by kentamphoto** [collective/Products.Quills#4]
Getting distribution for 'quills.app==1.8'.
error: docs/HISTORY.txt: No such file or directory
An error occured when trying to install quills.app 1.8. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'quills.app==1.8'.
Error: Couldn't install: quills.app 1.8

**Comment by skurfer** [comment]
It’s because `setup.py` refers to some text files that aren’t in the package at all (though they are in the repo). `Products.Quills` suffers from the same problem, so I’m surprised you even got to the part where it installs `quills.app`.
